language: bash
services: docker
before_install:
  - cd api-rest/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push pedromartinsb/mysql-vuttr-api-rest;
    docker push pedromartinsb/vuttr-api-rest;
  on:
    branch: master
notifications:
  email: false