version: '3.4'
services:
  db:
    image: pedromartinsb/mysql-vuttr-api-rest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: vuttr_api_rest
    ports:
      - "3308:3306"
    networks:
      - vuttr-network
  vuttr-api-rest:
    image: pedromartinsb/vuttr-api-rest
    restart: always
    build: ./api-rest
    working_dir: /api-rest
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./api-rest:/api-rest  
      - ~/.m2:/root/.m2
    ports:
      - "3000:3000"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - vuttr-network
networks:
    vuttr-network:
        driver: bridge    
